In [1]:
from api.riot_api_routes import *
from api.variables import SERVER_ROUTES, SERVER_REAL_NAME_TO_ROUTE, DIVISIONS, TIERS, GAME_TYPE,MAIN_GAMEMODE,RANKED_QUEUES, MATCHES_STATS_KEYS

import json
from django.conf import settings
from os import path
import os
import random

import pandas as pd
from time import sleep

league_data_route=path.join(settings.PREPROCESS_PATH, "league_data.json")
player_sample_route=path.join(settings.PREPROCESS_PATH, "player_sample.json")
matches_sample_route=path.join(settings.PREPROCESS_PATH, "matches_sample.csv")
champ_ban_file=path.join(settings.PREPROCESS_PATH, "champ_ban.csv")
champ_data_file=path.join(settings.PREPROCESS_PATH, "champ_data.csv")

In [3]:
champ_data = pd.read_csv(champ_data_file)
champ_data

,championId,teamId,role,lane,spell1Id,spell2Id,gameDuration,win,item0,item1,...,perk1,perk2,perk3,perk4,perk5,perkPrimaryStyle,perkSubStyle,statPerk0,statPerk1,statPerk2
0,16,100,DUO_SUPPORT,MIDDLE,4,7,1285,True,3853,3111,...,8226,8210,8237,8473,8453,8200,8400,5008,5002,5002
1,64,100,NONE,JUNGLE,11,4,1285,True,3111,1400,...,9111,9105,8014,8143,8135,8000,8100,5005,5008,5002
2,6,100,SOLO,TOP,4,12,1285,True,1055,1053,...,9111,9105,8014,8429,8451,8000,8400,5008,5008,5002
3,21,100,SOLO,BOTTOM,4,1,1285,True,1055,3508,...,9101,9104,8014,8275,8236,8000,8200,5005,5008,5002
4,34,100,DUO_CARRY,MIDDLE,4,12,1285,True,1056,3040,...,8226,8210,8236,8304,8347,8200,8300,5005,5008,5003
5,267,200,DUO_SUPPORT,BOTTOM,4,14,1285,False,3851,3174,...,8226,8210,8237,8345,8347,8200,8300,5008,5008,5002
6,60,200,NONE,JUNGLE,11,4,1285,False,1402,2031,...,8126,8138,8105,8275,8232,8100,8200,5005,5008,5002
7,63,200,SOLO,MIDDLE,4,14,1285,False,3165,1056,...,8226,8210,8237,8009,8014,8200,8000,5007,5008,5003
8,51,200,DUO_CARRY,BOTTOM,7,4,1285,False,1055,3095,...,9101,9103,8014,8275,8236,8000,8200,5005,5008,5002
9,75,200,SOLO,TOP,7,6,1285,False,3078,1054,...,8313,8321,8347,8275,8234,8300,8200,5007,5002,5002
10,40,100,DUO_SUPPORT,BOTTOM,4,14,1811,True,3174,3504,...,8226,8210,8237,8345,8347,8200,8300,5008,5008,5001
11,103,100,SOLO,MIDDLE,14,4,1811,True,1056,3111,...,8139,8138,8135,8226,8210,8100,8200,5008,5002,5003
12,51,100,DUO_CARRY,BOTTOM,4,7,1811,True,1055,3095,...,9111,9103,8014,8139,8135,8000,8100,5008,5008,5002
13,27,100,SOLO,TOP,6,4,1811,True,3800,3116,...,9111,9105,8299,8139,8135,8000,8100,5008,5008,5002
14,56,100,NONE,JUNGLE,11,4,1811,True,1416,3111,...,9111,9104,8014,8143,8106,8000,8100,5005,5008,5002
15,36,200,SOLO,TOP,4,12,1811,False,3065,3009,...,8446,8473,8451,8304,8347,8400,8300,5007,5002,5001
16,4,200,SOLO,MIDDLE,4,14,1811,False,3100,1056,...,8224,8210,8236,8313,8345,8200,8300,5008,5008,5002
17,48,200,NONE,JUNGLE,11,4,1811,False,1416,3065,...,9111,9104,8299,8429,8453,8000,8400,5005,5008,5001
18,267,200,DUO_SUPPORT,BOTTOM,7,4,1811,False,3853,3107,...,8226,8210,8236,8345,8347,8200,8300,5007,5008,5003
19,107,200,DUO_CARRY,BOTTOM,4,14,1811,False,1001,3077,...,9111,9104,8299,8143,8105,8000,8100,5005,5008,5002
20,64,100,NONE,JUNGLE,11,4,2361,True,3111,3026,...,9111,9104,8299,8304,8347,8000,8300,5005,5008,5002
21,875,100,SOLO,TOP,14,4,2361,True,3153,3075,...,9111,9104,8299,8275,8237,8000,8200,5007,5008,5003
22,157,100,SOLO,MIDDLE,4,14,2361,True,3153,3033,...,9111,9103,8014,8275,8236,8000,8200,5005,5008,5001
23,267,100,DUO_SUPPORT,BOTTOM,4,14,2361,True,3853,3504,...,8226,8233,8237,8453,8473,8200,8400,5008,5008,5002
24,81,100,DUO_CARRY,BOTTOM,4,7,2361,True,2055,3153,...,8009,9103,8014,8226,8210,8000,8200,5005,5008,5002
25,498,200,DUO_CARRY,BOTTOM,4,7,2361,False,3026,3508,...,9111,9103,8017,8275,8236,8000,8200,5005,5008,5002
26,59,200,NONE,JUNGLE,11,4,2361,False,2031,3193,...,9111,9104,8014,8143,8105,8000,8100,5005,5008,5002
27,57,200,SOLO,MIDDLE,12,4,2361,False,3109,3193,...,8446,8429,8453,8345,8352,8400,8300,5005,5008,5002
28,26,200,DUO_SUPPORT,BOTTOM,4,14,2361,False,3157,3853,...,8226,8233,8237,8313,8345,8200,8300,5007,5008,5001
29,39,200,SOLO,TOP,12,4,2361,False,1011,3153,...,9111,9104,8014,8345,8352,8000,8300,5005,5008,5002
30,86,100,SOLO,TOP,14,4,1203,False,2031,3078,...,9111,9104,8014,8275,8234,8000,8200,5005,5008,5002
31,61,100,SOLO,MIDDLE,12,4,1203,False,2033,3285,...,8226,8210,8237,8352,8345,8200,8300,5008,5008,5003
32,21,100,DUO_CARRY,BOTTOM,7,4,1203,False,1055,1055,...,9111,9103,8014,8275,8236,8000,8200,5005,5008,5002
33,154,100,NONE,JUNGLE,11,4,1203,False,1401,2031,...,8446,8429,8453,8304,8347,8400,8300,5007,5002,5002
34,412,100,DUO_SUPPORT,BOTTOM,4,14,1203,False,3190,3857,...,8463,8473,8451,8313,8345,8400,8300,5007,5002,5001
35,240,200,SOLO,TOP,12,4,1203,True,3748,1055,...,9111,9104,8299,8446,8473,8000,8400,5008,5008,5002
36,81,200,DUO_CARRY,BOTTOM,4,12,1203,True,1055,3004,...,8009,9103,8014,8226,8210,8000,8200,5005,5008,5002
37,40,200,DUO_SUPPORT,BOTTOM,4,7,1203,True,3504,3158,...,8226,8233,8237,8473,8453,8200,8400,5008,5008,5002
38,54,200,NONE,JUNGLE,11,4,1203,True,1402,3152,...,8143,8138,8106,8275,8236,8100,8200,5005,5008,5002
39,38,200,SOLO,MIDDLE,14,4,1203,True,3040,3041,...,8009,9105,8014,8138,8135,8000,8100,5008,5008,5003
40,59,100,NONE,JUNGLE,4,11,1967,False,1033,3077,...,9111,9105,8299,8139,8135,8000,8100,5005,5008,5001
41,126,100,SOLO,TOP,4,12,1967,False,1036,3142,...,8226,8233,8236,8345,8347,8200,8300,5008,5008,5002
42,145,100,SOLO,BOTTOM,4,7,1967,False,3508,3153,...,9111,9104,8014,8233,8275,8000,8200,5007,5008,5001
43,25,100,DUO_SUPPORT,MIDDLE,4,14,1967,False,3853,3157,...,8226,8210,8237,8345,8347,8200,8300,5007,5008,5002
44,105,100,DUO_CARRY,MIDDLE,4,14,1967,False,1056,3100,...,8143,8138,8105,8210,8237,8100,8200,5008,5008,5001
45,875,200,SOLO,TOP,4,12,1967,True,3053,3748,...,9111,9104,8299,8444,8453,8000,8400,5005,5008,5002
46,119,200,DUO_CARRY,BOTTOM,4,7,1967,True,3142,3139,...,9111,9103,8014,8275,8236,8000,8200,5005,5008,5002
47,555,200,DUO_SUPPORT,BOTTOM,4,14,1967,True,3857,3117,...,8446,8473,8453,8321,8347,8400,8300,5007,5008,5002
48,34,200,SOLO,MIDDLE,4,12,1967,True,3151,3040,...,8126,8138,8105,8009,8014,8100,8000,5008,5008,5003
49,79,200,NONE,JUNGLE,11,4,1967,True,1402,3157,...,8126,8136,8134,8313,8347,8100,8300,5005,5008,5002

In [7]:
len(champ_data)

50

In [8]:
champ_data['championId'].value_counts()

267    3
64     2
51     2
875    2
40     2
21     2
34     2
81     2
59     2
16     1
240    1
555    1
86     1
25     1
26     1
27     1
75     1
6      1
157    1
4      1
39     1
63     1
154    1
126    1
61     1
60     1
57     1
56     1
119    1
54     1
498    1
79     1
48     1
412    1
145    1
107    1
105    1
103    1
38     1
36     1
Name: championId, dtype: int64

In [5]:
champ_ban = pd.read_csv(champ_ban_file)
champ_ban.head()

   championId  pickTurn division tier   win
0         105         1  DIAMOND  III  True
1         122         2  DIAMOND  III  True
2           8         3  DIAMOND  III  True
3         350         4  DIAMOND  III  True
4          55         5  DIAMOND  III  True

In [6]:
champ_ban['championId'].value_counts()

 350    3
 131    3
 516    3
 238    3
 245    3
-1      2
 60     2
 89     2
 111    2
 142    2
 55     2
 8      2
 266    1
 17     1
 67     1
 23     1
 24     1
 154    1
 157    1
 62     1
 31     1
 875    1
 53     1
 38     1
 105    1
 30     1
 235    1
 51     1
 54     1
 56     1
 420    1
 122    1
 35     1
Name: championId, dtype: int64

In [24]:
winrate_on_ban=[]
for champ in champ_ban['championId'].unique():
    total = len(champ_ban.loc[(champ_ban['championId'] == champ)])
    win = len(champ_ban.loc[(champ_ban['championId'] == champ) & (champ_ban['win']==True)])
    winrate = win * 100 / total
    winrate_on_ban.append({
        "championId":champ,
        "winrate":winrate,
        "total":total
    })
pd.DataFrame(winrate_on_ban)

    championId     winrate  total
0          105  100.000000      1
1          122  100.000000      1
2            8  100.000000      2
3          350   66.666667      3
4           55   50.000000      2
5          238   66.666667      3
6          154    0.000000      1
7          131   33.333333      3
8          516   33.333333      3
9           24  100.000000      1
10          67  100.000000      1
11         245   33.333333      3
12          17    0.000000      1
13          54    0.000000      1
14          89    0.000000      2
15          53    0.000000      1
16         111  100.000000      2
17         266  100.000000      1
18          35  100.000000      1
19          -1    0.000000      2
20          60   50.000000      2
21         142   50.000000      2
22          30    0.000000      1
23         235    0.000000      1
24         875    0.000000      1
25         157  100.000000      1
26         420    0.000000      1
27          62    0.000000      1
28          23    0.000000      1
29          31  100.000000      1
30          51  100.000000      1
31          56  100.000000      1
32          38  100.000000      1

1

In [ ]:
winrate_on_ban['winrate']= * 100 / len(winrate_on_ban[])

In [19]:
len(winrate_on_ban['championId'])

50